<?php

namespace Database\Migrations;

use Carbon\Carbon;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

class Version20190120022808_populate_incorrect_dnh_template extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema): void
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $now = Carbon::now();

        $this->addSql(
            'INSERT INTO label_templates (template_name, template, created_at, updated_at) VALUES
            (\'incorrect_dnh\', \'N\nq792\nA180,5,0,4,3,3,N,"INCORRECT"\nA130,85,0,4,2,2,N,"DO NOT HACK LABEL"\n\nLO50,5,20,80\nLO50,105,20,20\n\nLO735,5,20,80\nLO735,105,20,20\n\nA10,170,0,4,1,1,N,"Correct Do Not Hack labels can be generated by"\nA10,210,0,4,1,1,N,"logging into the Hackspace Managment System(HMS)"\nA10,250,0,4,1,1,N,"https://hms.nottinghack.org.uk"\nA10,290,0,4,1,1,N,"and navigating to the \\\'Projects\\\' section"\n\n;qrcode and project Id\nb10,370,Q,s6,"https://guide.nottinghack.org.uk/do-not-hack.html"\nA220,370,0,4,1,1,N,"For more info about Do Not Hack"\nA220,400,0,4,1,1,N,"labels scan this QR code or visit:"\nA220,440,0,4,1,1,N,"https://guide.nottinghack.org.uk\"\n\nP1\n\', \'' . $now . '\', \'' . $now . '\')'
        );
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema): void
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('DELETE FROM label_templates WHERE template_name = \'incorrect_dnh\'');
    }
}
