#!/usr/bin/env bash

# copy live files to VM location
cp -r /vagrant/resources/assets/ /srv/vagrant/resources/
cp /vagrant/gulpfile.js /srv/vagrant/gulpfile.js

# run gulp
cd /srv/vagrant
gulp

# copy the results back
cp -r /srv/vagrant/public/css/ /vagrant/public/
cp -r /srv/vagrant/public/js/ /vagrant/public/
